defaults:
    - architecture: nasbench201like
    - optimizers: acml
    - operations: wo_conv1
    - schedulers: cos12
    - criteria: crossentropy
    - datasets: acml
    - training: acml 
hydra:
    run:
        dir: log/acml12/hydra
