# @package _group_
FirstCell:
    - Conv2d:
        in_channels: 3
        out_channels: out_channels
        kernel_size: 3
        padding: 1
    - BatchNorm2d:
        num_features: 16
ReductionCell:
    - ResidualBlock:
        in_channels: in_channels
        out_channels: in_channels*2
        stride: 2
        padding: 1
LastCell:
    - BatchNorm2d:
        num_features: in_channels
    - ReLU
    - AdaptiveAvgPool2d:
        output_size: 1
    - Serialize
    - Linear:
        in_features: 64
        out_features: 10
num_nodes:
    - 4
num_cells:
    - 5
num_blocks:
    - 3
channels:
    - [16, 32, 64]
cellcode: '2|11|133'
cellidx: 0
