# @package _group_
optimizers:
    - SGD:
        params: params
        lr: lr
        weight_decay: 0.0005
        momentum: momentum
        nesterov: True
options:
    lr:
        - 0.4
        - 0.2
        - 0.1
        - 0.05
        - 0.025
        - 0.0125
        - 0.00625
        - 0.003125
    momentum:
        - 0.9
