# @package _group_
optimizers:
    - SGD:
        params: params
        lr: lr
        weight_decay: 0.0005
        momentum: momentum
        nesterov: True
options:
    lr:
        - 0.2
        - 0.1
        - 0.05
        - 0.025
        - 0.01
    momentum:
        - 0.5
        - 0.7
        - 0.9
        - 0.99
        - 0.999
